Remove final from framework methods
Hilt generates a base class and somehow inherits the final modifier
in the process, causes compilation to fail when final methods are
overridden in the generated class hierarchy.

There errors from dagger generated classes were:

error: onCreate(Bundle) in ChooserActivity cannot override onCreate(Bundle) in Hilt_ChooserActivity
  overridden method is final

error: onDestroy() in ChooserActivity cannot override onDestroy() in Hilt_ChooserActivity
  overridden method is final

error: onCreate(Bundle) in ResolverActivity cannot override onCreate(Bundle) in Hilt_ResolverActivity
    protected final void onCreate(Bundle savedInstanceState) {

Flag: NA
Test: atest IntentResolver-tests-activity:com.android.intentresolver.v2
Bug: NA
Change-Id: Id925938ab9ce48caaa451a943547f1912058cfdf